Hotel_Final/Hotel_Final/Controllers/OrdersController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hotel_Final.Controllers
{
    public class OrdersController : BaseController
    {
        // GET: Orders
        [Authorize]
        public ActionResult OrderHistory()
        {
            
            if (User.IsInRole("admin"))
            {
                var adminslist = db.OrderHistories.OrderByDescending(ord => ord.CreatedDate).ToList();
                return View(adminslist);
            }

            var userid = User.Identity.GetUserId();

            var orders = db.OrderHistories.Where(order => order.ApplicationUserId == userid).ToList();

            return View(orders);
        }

    }
}

Hotel_Final/Hotel_Final/Controllers/PaidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Hotel_Final.Models;
using Microsoft.AspNet.Identity;

namespace Hotel_Final.Controllers
{
    public class PaidController : BaseController
    {
        // GET: Paid
        public ActionResult Index()
        {
            var model = new vwProdCat()
            {
                Categories = db.Categories.OrderBy(cat => cat.Id).Take(4).ToList(),
                Products = db.Products.Where(prod=>prod.CategoryId<5).OrderBy(prod => prod.OrderBy).ToList()
            };
            return View(model);
        }
        public JsonResult Products(int? id)
        {
            if (id == null)
            {
                return Json( db.Products.Where(prod => prod.CategoryId < 5).OrderBy(prod => prod.OrderBy).Select(prod=> new { prod.Name, prod.OrderBy, prod.Price, prod.Id }).ToList(), JsonRequestBehavior.AllowGet);
            }
            var product = db.Products.Where(prod => prod.CategoryId == id).OrderBy(o => o.OrderBy).ToList();
            if (product.Count==0)
            {

                return Json(new
                {
                    status = 405,
                    message = "Bu product siyahida yoxdur"
                }, JsonRequestBehavior.AllowGet);
            }

            return Json(
                product.Select(prod => new 
            { prod.Name, prod.OrderBy, prod.Price, prod.Id }),
                JsonRequestBehavior.AllowGet);

        }

        public JsonResult AddOrder(int id, int count)
        {
            if (id==null)
            {
                return Json(new { status = 407, message = "id bosdur" }, JsonRequestBehavior.AllowGet);
            };
            if (db.Products.Find(id).ProductCount<1)
            {
                return Json(new { status = 303, message = "Çox təəssüf bu məhsul hal-hazırda tükənib" }, JsonRequestBehavior.AllowGet);
            };

            var order = new OrderHistory();
            var userId = User.Identity.GetUserId();
            order.ProductId = id;
            order.OrderCount = count;
            order.ApplicationUserId = User.Identity.GetUserId();
            
            if (User.Identity.GetUserId() == null)
            {
                return Json(new { status = 432 }, JsonRequestBehavior.AllowGet);
            }
            order.CreatedDate.ToString("ddMMyyyy");
            db.OrderHistories.Add(order);
            if (db.Products.Find(id).Price != null)
            {
                var parsePrice = db.Products.Find(id).Price;
                order.TotalPrice = order.OrderCount * int.Parse(parsePrice);

            }
            else
            {
                order.TotalPrice.ToString("Ödənişsizdir");

            }
            db.Products.Find(id).ProductCount -= count;
            db.SaveChanges();
            
            return Json(new { status=200,id=order.Id},JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SendOrder(string Subject)
        {


            if (Subject =="undefined")
            {
                return RedirectToAction("Login", "Account");
            }

            var orderId = int.Parse(Subject);
           string Email = db.OrderHistories.Find(orderId).ApplicationUser.Email;




            var neworder = db.OrderHistories.Find(orderId);
           
            

            var body = "<p>Email From: {0} <br>Adi: {2} <br> Sayi: {1} <br> Qiymeti: {3} <br><br> Otel Nomresi: {4} </p>";
            var message = new MailMessage();
            message.To.Add(new MailAddress("ulviia@code.edu.az"));  // replace with valid value 
            message.From = new MailAddress(Email);  // replace with valid value
            message.Subject = "Yeni product";

            message.Body = string.Format(body, Email, neworder.OrderCount, neworder.Product.Name, neworder.TotalPrice,neworder.ApplicationUser.RoomNumber);
            message.IsBodyHtml = true;
            try
            {
                using (var smtp = new SmtpClient())
                {
                    var credential = new NetworkCredential
                    {
                        UserName = "hotelweb.93@gmail.com",  // replace with valid value
                        Password = "Hotel_123"  // replace with valid value
                    };
                    smtp.Credentials = credential;
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.EnableSsl = true;

                    smtp.Send(message);

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                if(ex.Message== "Failure sending mail.")
                {
                    db.Products.Find(neworder.ProductId).ProductCount += db.OrderHistories.FirstOrDefault(f=>f.Id==orderId).OrderCount;
                    db.Users.Find(neworder.ApplicationUserId).PayBalance -= db.OrderHistories.FirstOrDefault(f => f.Id == orderId).TotalPrice;
                    db.OrderHistories.Remove(neworder);
                    db.SaveChanges();
                    return RedirectToAction("Error", "Home");
                    
                }
                throw;
            }

           
            
        }
        
        }
}

Hotel_Final/Hotel_Final/Controllers/RestorantController.cs
using Hotel_Final.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hotel_Final.Controllers
{
    public class RestorantController : BaseController
    {
        // GET: Restorant
        public ActionResult Restoran()
        {

            var model = new vwProdCat()
            {
                Categories = db.Categories.OrderByDescending(cat => cat.Id).Take(5).ToList(),
                Products = db.Products.OrderBy(prod => prod.OrderBy).ToList()
            };
            return View(model);
        }
    }
}

Hotel_Final/Hotel_Final/Views/Shared/_Layout.cshtml
@using Hotel_Final.Models

@{ 
    Settings setting = ViewBag.Setting;
    var controllerName = this.ViewContext.RouteData.Values["Controller"].ToString().ToLower();

}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hotel</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">

    <link rel="stylesheet" href="~/Public/Css/animate.min.css">

    @*<link href="https://fonts.googleapis.com/css?family=Literata|Roboto|Roboto+Slab|Slabo+27px&display=swap"
          rel="stylesheet">*@
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    @RenderSection("css", required: false)
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Public/owlcarousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Public/owlcarousel/owl.theme.default.min.css">
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/Public/Sass/style.css?time=@DateTime.Now.ToFileTime()">
</head>
<body>
    <!-- Header start -->
    <header id="header" class="animated col-lg-12 col-sm-12">

        <!-- Navbar and toggle collapse begin -->
        <nav class=" navbar  navbar-expand-lg navbar-light container ">

            @Html.ActionLink(setting.Logo, "Index", "Home", new { area = "" }, new { @id = "Brand", @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-between " id="navbarSupportedContent">
                <ul class="navbar-nav ">
                    <li class="nav-item">
                        <a class="@(controllerName=="home"?"active ":"")nav-link" href=@Url.Action("Index", "Home")>Əsas səhifə <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="@(controllerName=="restorant"?"active ":"")nav-link" href=@Url.Action("Restoran","Restorant")>Restoran <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="@(controllerName=="paid"?"active ":"") nav-link" href=@Url.Action("Index","Paid")>İstəklər <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="@(controllerName=="orders"?"active ":"")nav-link" href=@Url.Action("OrderHistory","Orders")>Sifarişlərim <span class="sr-only">(current)</span></a>
                    </li>




                </ul>
                <div class="Login d-flex justify-content-between">
                    <a class="basket" href="/Orders/OrderHistory"><i class="fas fa-shopping-cart"></i><span></span></a>

                    @Html.Partial("_LoginPartial")
                </div>

            </div>
        </nav>
    </header>
    <!-- Header end -->
    @RenderBody()
    <div style="width: 100%; height: 401px;" class="load fixed-top">
        <img style="background-color: #343a404a; width: 100%; height: 100vh" src="~/Public/img/Spin-Preloader.gif" alt="Alternate Text" />
    </div>

    <!-- Start footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="margin left col-lg-4 col-md-6 col-sm-12">
                    <h4>@setting.Logo</h4>
                    <p class="mt-4 mb-4">
                        @setting.Desc
                    </p>
                    <ul class="list-unstyled sosial">
                        <li>
                            <a href=@setting.Facebook><i class="fab fa-facebook-f"></i> </a>
                        </li>
                        <li>
                            <a href=@setting.Twitter><i class="fab fa-twitter"></i> </a>
                        </li>
                        <li>
                            <a href=@setting.GooglePlus><i class="fab fa-google-plus-g"></i></i> </a>
                        </li>
                        <li>
                            <a href=@setting.Instagram><i class="fab fa-instagram"></i></a>
                        </li>
                        <li>
                            <a href=@setting.Youtube><i class="fab fa-youtube"></i> </a>
                        </li>
                    </ul>
                </div>
                <div class="margin  middle col-lg-4 col-md-6 col-sm-12">
                    <h4 class="ml-3">@setting.Title</h4>
                    <ul class="list-group ml-3 list-group-flush">
                        <li class="list-group-item border-top-0"><i class="fas fa-map-marker-alt"></i><a style="color:white; font-size:20px; text-decoration:none" href=@setting.Locations>Af Biznes House</a> </li>
                        <li class="list-group-item"><i class="fas fa-phone"></i>@setting.Phones</li>
                        <li class="list-group-item"> <i class="fas fa-mobile-alt"></i>3333-2222-1111</li>
                        <li class="list-group-item"><i class="fas fa-envelope"></i> <a style="color:white; font-size:20px; text-decoration:none" href=@Url.Action("Index","Contact")>@setting.Email</a></li>
                    </ul>
                </div>
                <div class="margin right col-lg-4 col-md-6 col-sm-12">
                    <h4 class="ml-3">NEWSLETTER</h4>
                    <p class="mt-4 mb-4">Saytımız barədə sizə bildirişlərin gəlməsini istəyirsinizsə emailinizi bizə göndərin</p>
                    <form>
                        <div class="input-group">
                            <input class="form-control" type="text" name="Subscribe" id="Subscribe">
                        </div>
                        <button type="submit" class="mt-4 sub btnLogin">Subscribe</button>

                    </form>
                </div>

            </div>


            <div class="end mt-3">@setting.Info</div>
        </div>

    </footer>


    <!-- end footer -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>






    @Scripts.Render("~/bundles/jquery")
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>

    @RenderSection("scripts", required: false)


    @Scripts.Render("~/bundles/bootstrap")
    @*<script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
        <script src="http://threejs.org/examples/js/libs/stats.min.js"></script>*@
    <script src="~/Public/owlcarousel/owl.carousel.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>


    <script src="~/Scripts/main.js?time=@DateTime.Now.ToFileTime()"></script>
</body>

</html>